Bump Flux components to latest
aws/eks-anywhere-build-tooling pull request #1053
Opened 2022-07-13 04:57 UTC by abhay-krishna

Bumping Flux components to latest:
- [flux2](https://github.com/fluxcd/flux2/releases/tag/v0.31.3)
- [helm-controller](https://github.com/fluxcd/helm-controller/releases/tag/v0.22.1)
- [kustomize-controller](https://github.com/fluxcd/kustomize-controller/releases/tag/v0.26.2)
- [notification-controller](https://github.com/fluxcd/notification-controller/releases/tag/v0.24.0)
- [source-controller](https://github.com/fluxcd/source-controller/releases/tag/v0.25.9)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-13 05:03 UTC, abhay-krishna commented
/hold

2022-07-14 12:10 UTC, TerryHowe requested changes

2022-07-15 04:35 UTC, abhay-krishna commented on projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
> +![Version](https://img.shields.io/badge/version-v0.4.5--rc5-blue)
This badge provider requires for tags with a dash in them to use two dashes to render properly: #953

2022-07-15 15:32 UTC, jiayiwang7 approved these changes

2022-07-15 17:40 UTC, abhay-krishna commented
/unhold

2022-07-15 17:43 UTC, abhay-krishna commented
/override cluster-api-provider-cloudstack-tooling-presubmit
/override eks-anywhere-packages-image-tooling-presubmit
/override flux-tooling-presubmit
/override helm-controller-tooling-presubmit
/override kustomize-controller-tooling-presubmit
/override notification-controller-tooling-presubmit
/override source-controller-tooling-presubmit

Overriding these presubmits because I closed the PR (by mistake) and then re-opened, and they got re-triggered. They passed already.

2022-07-15 17:45 UTC, merged