Build Cluster Autoscaler
aws/eks-anywhere-build-tooling pull request #1268
Opened 2022-09-06 21:51 UTC by jonathanmeier5

*Issue #, if available:*
https://github.com/aws/eks-anywhere/issues/3187

*Description of changes:*
Building cluster autoscaler image

2022-09-06 22:04 UTC, jaxesn requested changes
Great start!

2022-09-06 22:04 UTC, jaxesn commented on projects/kubernetes/autoscaler/1-20/GIT_TAG
> +cluster-autoscaler-1.20.3
This may open a can of worms that isnt worth it, but packages doesnt support 1-20. we may be able to get away just not building 1.20 for this one?

2022-09-06 22:04 UTC, jaxesn commented on projects/kubernetes/autoscaler/Makefile
> +BINARY_TARGET_FILES=cluster-autoscaler-amd64
remove this arch at the end

2022-09-06 22:04 UTC, jaxesn commented on projects/kubernetes/autoscaler/docker/linux/Dockerfile
> +COPY _output/$RELEASE_BRANCH/bin/autoscaler/$TARGETOS-$TARGETARCH/cluster-autoscaler-amd64 /cluster-autoscaler
remove the arch suffix

2022-09-06 22:04 UTC, jaxesn commented on projects/kubernetes/autoscaler/docker/linux/Dockerfile
> +USER nobody
this should be fine, but keep in mind in case we get issues when we test the image

2022-09-07 02:27 UTC, TerryHowe commented
Nice start!

2022-09-08 00:28 UTC, jaxesn requested changes
This looks pretty great! I think we could finish this up and assuming the cdk changes are in we could merge and then do the helm chart in a follow up?

2022-09-08 00:28 UTC, jaxesn commented on projects/kubernetes/autoscaler/Makefile
> +BASE_IMAGE_NAME?=eks-distro-minimal-base
Remove a newline

2022-09-08 00:28 UTC, jaxesn commented on projects/kubernetes/autoscaler/Makefile
> +include $(BASE_DIRECTORY)/Common.mk
Add another newline after this include

2022-09-08 00:28 UTC, jaxesn commented on projects/kubernetes/autoscaler/Makefile
> +	cp $(REPO)/LICENSE $@
Is this tabing correct?

2022-09-08 00:28 UTC, jaxesn commented on projects/kubernetes/autoscaler/README.md
> +The source of truth for golang build version is [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-go-version-should-be-used-to-compile-ca).
Copy one of the other projects updating section and use as a template to fill this out some.

2022-09-08 00:28 UTC, jaxesn commented on build/lib/run_target_docker.sh
> +RELEASE_BRANCH="${4:-"1-20"}"
I'm going to double check this change isn't an issue for other project builds.

2022-09-08 00:30 UTC, jaxesn commented on Common.mk
> +	    if [ -d "$$version" ]; then \
Let's just add a comment, above the target, saying something about how we allow projects to skip building specific versions by not including those folders. It's admittedly a bit magical and potentially will hide issues if someone accidentally forgets to add all the folders, I just want this documented in some way for future us to try and determine what the hell we were thinking.

2022-09-09 21:38 UTC, jaxesn approved these changes
Great job! On to the helm chart!

2022-09-09 22:00 UTC, abhay-krishna commented
/approve

2022-09-09 22:01 UTC, merged