Update hello-eks-anywhere json schema
aws/eks-anywhere-build-tooling pull request #1557
Opened 2022-11-11 14:23 UTC by ivyostosh

In order for the json schema to be usable on the helm level, we need to add in additional fields.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-11 14:49 UTC, TerryHowe commented on projects/aws-containers/hello-eks-anywhere/helm/schema.json
> +    },
Not sure we'd want to expose this or repository. Kind of goes against what were are trying to do here. No doubt we do in other packages, but I would argue we shouldn't. With either of these in there, someone that only had permissions to create packages resources could easily get access to other resources.

2022-11-11 14:51 UTC, TerryHowe commented on projects/aws-containers/hello-eks-anywhere/helm/schema.json
> +    },
I think adding namespace here would be confusing because we aren't going to use it from the package `config` we'll use `targetNamespace`

2022-11-11 16:51 UTC, TerryHowe requested changes
I think we should set `"additionalProperties": true`

2022-11-14 15:42 UTC, ivyostosh commented
We will merge https://github.com/aws/eks-anywhere-build-tooling/pull/1563 instead

2022-11-14 15:42 UTC, closed without merging