add capi patch to enable kubeadm feature flags mutation
aws/eks-anywhere-build-tooling pull request #2958
Opened 2024-02-28 02:38 UTC by abhinavmpandey08

*Description of changes:*
Currently, kubeadm feature flags are immutable which cause issues when upgrading a cluster from 1.28 to 1.29 as we try to disable the `EtcdLearnerMode` feature flag. This gets blocked by webhooks because the feature flag itself is immutable.

This PR patches CAPI based on this upstream PR https://github.com/kubernetes-sigs/cluster-api/pull/10154 to make this field mutable.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-28 02:44 UTC, tatlat commented
/lgtm

2024-02-28 02:47 UTC, tatlat approved these changes

2024-02-28 04:17 UTC, abhay-krishna requested changes

2024-02-28 04:17 UTC, abhay-krishna commented on projects/kubernetes-sigs/cluster-api/patches/0041-enable-kubeadm-feature-flags-mutation.patch
> + ...nable-kubeadm-feature-flags-mutation.patch | 1111 +++++++++++++++++
let's remove this patch file from the patch and keep only the Go files.

2024-02-28 17:22 UTC, abhay-krishna approved these changes

2024-02-28 17:30 UTC, abhinavmpandey08 commented
/approve

2024-02-28 17:31 UTC, merged

2024-02-28 17:46 UTC, abhinavmpandey08 commented
/cherry-pick main

2024-03-01 22:01 UTC, abhinavmpandey08 commented
/cherry-pick main