bump troubleshoot version
aws/eks-anywhere-build-tooling pull request #317
Opened 2022-01-05 18:08 UTC by danbudris

*Issue #, if available:*

*Description of changes:*
Bump troubleshoot version to latest release.

Checked the Makefile changes, no additional build flags or major modifications that would make it necessary to update the build logic we currently use AFAICT.

Tested functionality (`generate support-bundle` and `generate support-bundle-config`) of EKS-A by setting `MR_TOOLS_DISABLE=true` and using the latest release executable. 

I believe we have go 1.17 in builder base as well.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-05 18:09 UTC, jaxesn requested changes
Can you add an updating section to the readme?  Look at the flux project for an example.

The build will fail and youll need to update the checksums, just pull them out of the build output.

2022-01-05 18:24 UTC, danbudris commented
> 

yeah the flux one is very helpful generally

2022-01-05 22:30 UTC, danbudris commented
/retest

2022-01-05 23:20 UTC, danbudris commented
/retest

2022-01-06 15:19 UTC, danbudris commented
/retest

2022-01-06 15:22 UTC, jaxesn commented on projects/replicatedhq/troubleshoot/README.md
> +#### Get and build Troubleshoot locally
Why give these instructions? Instead why don't we just us the makefile in this repo for building locally.  ref: https://github.com/aws/eks-anywhere-build-tooling/blob/main/docs/development/building-locally.md

2022-01-06 19:19 UTC, merged