[WIP] Bump capi to v1.8.3
aws/eks-anywhere-build-tooling pull request #3805
Opened 2024-09-27 09:59 UTC by sp1999

## Description of changes
This PR bumps CAPI to the latest v1.8.3 to support Kubernetes 1.31.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-27 09:59 UTC, sp1999 commented
/hold

2024-09-30 04:12 UTC, sp1999 commented
/approve

2024-09-30 16:10 UTC, tatlat requested changes

2024-09-30 16:10 UTC, tatlat commented on projects/kubernetes-sigs/cluster-api/patches/0041-Update-generated-files-by-running-make-generate.patch
Can this be part of the previous patch instead of it's own patch?

2024-09-30 22:57 UTC, tatlat commented
/lgtm

2024-09-30 23:02 UTC, sp1999 commented
/unhold

2024-09-30 23:22 UTC, tatlat approved these changes

2024-09-30 23:22 UTC, merged

2024-10-01 00:31 UTC, rahulbabu95 commented on projects/kubernetes-sigs/cluster-api/patches/0001-Update-coredns-corefile-migration-to-support-1.11.3.patch
Don't think we need this patch anymore. corefile-migration v1.0.23 supports coredns version 1.11.3 that eks-d currently ships.