upgrade to v2.8.1 and security patch
aws/eks-anywhere-build-tooling pull request #741
Opened 2022-04-30 03:45 UTC by vincentni

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-30 10:33 UTC, TerryHowe approved these changes
/lgtm

2022-04-30 12:27 UTC, jaxesn commented on projects/distribution/distribution/Makefile
>  EXTRA_GOBUILD_FLAGS=-tags include_oss,include_gcs
The s and w should already be being set from the default flags in https://github.com/aws/eks-anywhere-build-tooling/blob/main/Common.mk#L321. was there an issue you saw here?

2022-04-30 12:29 UTC, jaxesn requested changes
Could you add an updating section to the readme, we've been gradually doing this as we update projects? Check out the cluster api project readme for an example since it also deals with patches.

2022-05-02 22:49 UTC, jaxesn approved these changes

2022-05-02 22:51 UTC, vincentni commented
/approve

2022-05-02 22:52 UTC, merged