upgrade to v2.5.0 and security patch
aws/eks-anywhere-build-tooling pull request #742
Opened 2022-04-30 03:46 UTC by vincentni

*Issue #, if available:*

*Description of changes:*
upgrade Harbor to v2.5.0
upgrade Harbor Helm to v1.9.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-30 10:34 UTC, TerryHowe approved these changes
/lgtm

2022-04-30 12:30 UTC, jaxesn requested changes
Could you add an updating section to the readme especially since there are a number of versions being updated here and changes required in the helm script files?

2022-05-02 22:50 UTC, jaxesn commented on projects/goharbor/harbor/Makefile
> +$(call IMAGE_TARGETS_FOR_NAME, harbor-portal): clean-go-cache
i am going to move this somewhere else in another PR

2022-05-02 22:50 UTC, jaxesn approved these changes

2022-05-02 22:55 UTC, vincentni commented
/approve

2022-05-02 23:22 UTC, merged